export interface Product {
  id: number;
  name: string;
  category: string;
  subcategory: string;
  gender: 'men' | 'women';
  color: string;
  colors: string[];
  style: string[];
  occasion: string[];
  price: string;
  oldPrice?: string | null;
  imageUrl: string;
  sizes: string[];
  stock: 'in stock' | 'low stock' | 'out of stock';
  isNew: boolean;
  isSale: boolean;
  rating: number;
  reviews: number;
  description: string;
}

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Aether Linen Blouse",
    category: "Women's Tops",
    subcategory: "Tops",
    gender: "women",
    color: "white",
    colors: ["white"],
    style: ["casual", "chic", "work"],
    occasion: ["work", "date", "graduation", "picnic"],
    price: "49.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1524239124694-de99d46925b0?w=400&h=500&fit=crop&q=80",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: "in stock",
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 128,
    description: "A breathable, high-grade linen blouse with a relaxed silhouette and pearl-finish buttons."
  },
  {
    id: 2,
    name: "Midnight Silk Midi",
    category: "Women's Dresses",
    subcategory: "Dresses",
    gender: "women",
    color: "black",
    colors: ["black"],
    style: ["elegant", "chic"],
    occasion: ["special events", "date", "wedding", "dinner"],
    price: "129.00",
    oldPrice: "189.00",
    imageUrl: "https://images.unsplash.com/photo-1485231183947-667a06ed93a9?w=400&h=500&fit=crop&q=80",
    sizes: ["S", "M", "L"],
    stock: "in stock",
    isNew: false,
    isSale: true,
    rating: 4.9,
    reviews: 84,
    description: "Pure mulberry silk dress that flows effortlessly, featuring a delicate side slit and adjustable straps."
  },
  {
    id: 3,
    name: "Urban Biker Jacket",
    category: "Women's Outerwear",
    subcategory: "Jackets",
    gender: "women",
    color: "black",
    colors: ["black"],
    style: ["streetwear", "sporty"],
    occasion: ["going out", "daily casual", "travel"],
    price: "199.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=400&h=500&fit=crop&q=80",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: "low stock",
    isNew: true,
    isSale: false,
    rating: 4.8,
    reviews: 215,
    description: "Hand-crafted faux leather jacket with silver hardware and a structured, cropped fit."
  },
  {
    id: 4,
    name: "High-Rise Ivory Trousers",
    category: "Women's Bottoms",
    subcategory: "Pants",
    gender: "women",
    color: "ivory",
    colors: ["ivory"],
    style: ["chic", "elegant", "work"],
    occasion: ["work", "special events", "graduation"],
    price: "85.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=500&fit=crop&q=80",
    sizes: ["24", "26", "28", "30", "32"],
    stock: "in stock",
    isNew: false,
    isSale: false,
    rating: 4.6,
    reviews: 92,
    description: "Tailored wide-leg trousers in a premium wool blend, designed to elongate the silhouette."
  },
  {
    id: 5,
    name: "Sand Cashmere Sweater",
    category: "Women's Tops",
    subcategory: "Tops",
    gender: "women",
    color: "beige",
    colors: ["beige"],
    style: ["casual", "chic"],
    occasion: ["daily casual", "work", "travel"],
    price: "110.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1620791144139-127c79313842?w=400&h=500&fit=crop&q=80",
    sizes: ["S", "M", "L", "XL"],
    stock: "in stock",
    isNew: true,
    isSale: false,
    rating: 4.9,
    reviews: 156,
    description: "Ultra-soft 100% cashmere knit with a classic crew neck and ribbed cuffs for timeless warmth."
  },
  {
    id: 6,
    name: "Soleil Floral Dress",
    category: "Women's Dresses",
    subcategory: "Dresses",
    gender: "women",
    color: "pastel",
    colors: ["pastel"],
    style: ["casual", "chic"],
    occasion: ["picnic", "date", "beach", "birthday"],
    price: "75.00",
    oldPrice: "95.00",
    imageUrl: "https://images.unsplash.com/photo-1496741475852-45943bc9280d?w=400&h=500&fit=crop&q=80",
    sizes: ["XS", "S", "M", "L"],
    stock: "in stock",
    isNew: false,
    isSale: true,
    rating: 4.5,
    reviews: 67,
    description: "A light-weight viscose dress with a hand-painted floral motif and a flattering wrap waist."
  },
  {
    id: 7,
    name: "Onyx Wool Overcoat",
    category: "Women's Outerwear",
    subcategory: "Jackets",
    gender: "women",
    color: "black",
    colors: ["black"],
    style: ["elegant", "work"],
    occasion: ["special events", "work", "funeral", "dinner"],
    price: "250.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1539106397-59c90f4c0255?w=400&h=500&fit=crop&q=80",
    sizes: ["S", "M", "L", "XL"],
    stock: "low stock",
    isNew: false,
    isSale: false,
    rating: 5.0,
    reviews: 42,
    description: "Premium double-breasted wool coat with a satin lining and structured shoulders."
  },
  {
    id: 8,
    name: "Classic Oxford Shirt",
    category: "Men's Tops",
    subcategory: "Tops",
    gender: "men",
    color: "white",
    colors: ["white"],
    style: ["casual", "work"],
    occasion: ["work", "graduation", "interview", "date"],
    price: "55.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1602810319456-dc202f378c8f?w=400&h=500&fit=crop&q=80",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: "in stock",
    isNew: false,
    isSale: false,
    rating: 4.7,
    reviews: 189,
    description: "Pre-washed heavy cotton Oxford shirt with a button-down collar and a modern tailored fit."
  },
  {
    id: 9,
    name: "Tapered Khaki Chinos",
    category: "Men's Bottoms",
    subcategory: "Pants",
    gender: "men",
    color: "khaki",
    colors: ["khaki"],
    style: ["casual", "work"],
    occasion: ["daily casual", "work", "picnic", "travel"],
    price: "65.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1503449377703-9e1d2363572a?w=400&h=500&fit=crop&q=80",
    sizes: ["30", "32", "34", "36"],
    stock: "in stock",
    isNew: false,
    isSale: false,
    rating: 4.6,
    reviews: 112,
    description: "Stretch-cotton twill chinos with a smooth finish and a refined tapered leg for all-day comfort."
  },
  {
    id: 10,
    name: "Heritage Denim Jacket",
    category: "Men's Outerwear",
    subcategory: "Jackets",
    gender: "men",
    color: "blue",
    colors: ["blue"],
    style: ["streetwear", "casual"],
    occasion: ["daily casual", "going out", "concert", "travel"],
    price: "95.00",
    oldPrice: "120.00",
    imageUrl: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=800&q=80",
    sizes: ["S", "M", "L", "XL"],
    stock: "in stock",
    isNew: false,
    isSale: true,
    rating: 4.8,
    reviews: 324,
    description: "Raw indigo denim jacket that develops unique character over time, featuring copper shank buttons."
  },
  {
    id: 11,
    name: "Steel Merino Polo",
    category: "Men's Tops",
    subcategory: "Tops",
    gender: "men",
    color: "grey",
    colors: ["grey"],
    style: ["chic", "work"],
    occasion: ["work", "date", "dinner"],
    price: "70.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1617137962151-e3f6430b2034?w=400&h=500&fit=crop&q=80",
    sizes: ["M", "L", "XL", "XXL"],
    stock: "in stock",
    isNew: true,
    isSale: false,
    rating: 4.9,
    reviews: 58,
    description: "Finely knit merino wool polo with a soft hand-feel and natural temperature regulation."
  },
  {
    id: 12,
    name: "Regent Navy Suit",
    category: "Men's Suits",
    subcategory: "Suits",
    gender: "men",
    color: "navy",
    colors: ["navy"],
    style: ["elegant", "work"],
    occasion: ["wedding", "graduation", "interview", "special events"],
    price: "350.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1594938298755-99d343f4233c?w=400&h=500&fit=crop&q=80",
    sizes: ["38R", "40R", "42R", "44R"],
    stock: "low stock",
    isNew: false,
    isSale: false,
    rating: 5.0,
    reviews: 29,
    description: "A masterfully tailored suit in Super 120s wool, featuring a half-canvas construction."
  },
  {
    id: 13,
    name: "Shadow Chelsea Boots",
    category: "Men's Shoes",
    subcategory: "Shoes",
    gender: "men",
    color: "black",
    colors: ["black"],
    style: ["chic", "streetwear"],
    occasion: ["going out", "date", "dinner", "travel"],
    price: "150.00",
    oldPrice: "195.00",
    imageUrl: "https://images.unsplash.com/photo-1635397174119-041911acc99b?w=400&h=500&fit=crop&q=80",
    sizes: ["8", "9", "10", "11", "12"],
    stock: "in stock",
    isNew: false,
    isSale: true,
    rating: 4.7,
    reviews: 142,
    description: "Premium Italian suede boots with elastic side panels and a durable stacked leather sole."
  },
  {
    id: 14,
    name: "Iconic Graphic Tee",
    category: "Men's Tops",
    subcategory: "Tops",
    gender: "men",
    color: "white",
    colors: ["white"],
    style: ["streetwear", "sporty", "casual"],
    occasion: ["daily casual", "gym", "beach", "picnic"],
    price: "35.00",
    oldPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1521572267396-84844ad2d3ef?w=400&h=500&fit=crop&q=80",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: "in stock",
    isNew: true,
    isSale: false,
    rating: 4.4,
    reviews: 210,
    description: "Heavy-weight organic cotton tee with a screen-printed minimalist graphic on the back."
  }
];
